
services:
  rag:
    image: 'rag:latest'
    ports: 
      - '8080:8080'
    depends_on:
      - chroma
      - ollama
    environment:
      APP_CHROMA_ENDPOINT: http://chroma:8000
      APP_OLLAMA_ENDPOINT: http://ollama:11434
      SPRING_AI_VECTORSTORE_CHROMA_ENDPOINT: http://chroma:8000


  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/chroma/.chroma
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    command: ["serve"]
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_MODELS: /root/.ollama/models
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 15m

volumes:
  chroma_data:
  ollama_data:
